[FRONT-809] Add Room Modal
streamr-dev/chat pull request #41
Opened 2022-02-01 01:14 UTC by its-edmund

2022-02-01 11:40 UTC, mondoreale requested changes
Let's fix the console, `stroke-*` attrs and it's g2g.

2022-02-01 11:40 UTC, mondoreale commented on package.json
> -  "name": "the-chat-app",
If that's prettier then let's revert. Otherwise npm will reformat it back again.

2022-02-16 09:52 UTC, hpihkala commented
Just to check - what's implemented in this PR? Is this this?
<img width="534" alt="Screenshot 2022-02-16 at 10 26 15" src="https://user-images.githubusercontent.com/1263120/154239456-55ce6ec5-5fbc-4183-8a6c-bd8d0780c067.png">

2022-02-16 09:56 UTC, mondoreale commented
@hpihkala, that's the one.

2022-02-22 09:50 UTC, merged